#!/bin/bash

# Setup script for Demo Mode
# This script creates a .env file with demo mode enabled

echo "🎭 Setting up Demo Mode for MRE Appointment Demo"
echo ""

# Check if .env already exists
if [ -f .env ]; then
  echo "⚠️  Warning: .env file already exists!"
  read -p "Do you want to overwrite it? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Setup cancelled. Existing .env file was not modified."
    exit 1
  fi
fi

# Prompt for API URL
read -p "Enter your API URL (e.g., https://api.example.com/api): " api_url

# Create .env file
cat > .env << EOF
# Demo Mode Configuration
# Generated by setup-demo.sh

# Demo Mode - Authentication disabled
VITE_DEMO_MODE=true

# API Configuration
VITE_API_URL=${api_url}

# Authentication (not used in demo mode)
VITE_AUTH_REDIRECT_URL=http://localhost:3000

# Google Maps API Key (optional)
VITE_MAPS_API_KEY=
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "📝 Demo Mode is now enabled with the following configuration:"
echo "   - VITE_DEMO_MODE=true"
echo "   - VITE_API_URL=${api_url}"
echo ""
echo "🚀 Next steps:"
echo "   1. Install dependencies: npm install"
echo "   2. Start dev server: npm run dev"
echo ""
echo "📖 For more information, see DEMO_MODE.md"
echo ""
echo "⚠️  Remember: NEVER enable demo mode in production!"

